# The Docker image that will be used to build your app
image: lst
cache:
  key: hugo-binary-v0.148.2
  paths:
  - hugo
pages:
  script:
  - |
    if [ ! -f ./hugo ]; then
      echo "Hugo binary not found. Downloading..."
      curl -L -o hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v0.148.2/hugo_extended_0.148.2_linux-amd64.tar.gz
      tar -xzf hugo.tar.gz
      chmod +x ./hugo
    else
      echo "Using cached Hugo binary."
    fi
  - "./hugo"
  artifacts:
    paths:
    - public
  only:
  - main