# .github/workflows/release.yml
name: Build & Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 或者是您的主分支名
    tags:
      - 'v*'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.148.2'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  release_zip:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: .
      - name: Create ZIP
        run: |
          mkdir site-archive
          tar -xvf artifact.tar -C site-archive
          cd site-archive && zip -r "../site-${{ github.ref_name }}.zip" .
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: site-${{ github.ref_name }}.zip
          generate_release_notes: true
